--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/theRankShop
build-by-default: true
branches:
- master
- development
- pm5
projects:
  theRankShop:
    icon: "icon.png"
    path: ""
    php: 8.1
    libs:
      - src: https://poggit.pmmp.io/ci/supercrafter333/FormAPI/libFormAPI
      - src: https://poggit.pmmp.io/ci/supercrafter333/yamlcomments/yamlcomments
...