name: theRankShop
version: 1.2.0
api: 4.0.0
main: supercrafter333\theRankShop\theRankShop
author: supercrafter333
description: A simple and user-friendly rank shop plugin with extension support and multi-language-system.

softdepend:
  - "GroupsAPI"
  - "BedrockEconomy"
  - "PurePerms"
  - "EconomyAPI"

permissions:
  theRankShop.cmd:
    description: Command permission
    default: true
  theRankShop.cmd.addrank:
    description: Command permission
    default: op
  theRankShop.cmd.removerank:
    description: Command permission
    default: op