name: theRankShop
version: 1.5.0-dev
api: 5.0.0
main: supercrafter333\theRankShop\theRankShop
author: supercrafter333
description: A simple and user-friendly rank shop plugin with extension support and multi-language-system.

softdepend:
  - "GroupsAPI"
  - "GroupSystem"
  - "RankSystem"
  - "BedrockEconomy"

permissions:
  theRankShop.cmd:
    description: Command permission
    default: true
  theRankShop.cmd.addrank:
    description: Command permission
    default: op
  theRankShop.cmd.removerank:
    description: Command permission
    default: op