name: theRankShop
version: 1.0.0
api: 4.0.0
main: supercrafter333\theRankShop\theRankShop
author: supercrafter333
description: A simple and user-friendly rank shop plugin with extension support and multi-language-system.

permissions:
  theRankShop.cmd:
    description: Command permission
    default: true